import { expect, test } from '@playwright/test';
import { AssetsPage } from './pages/assets-page';
import { MAX_ITEMS } from '@/constants/lists';
import { participantConfig } from './utils/tests-config';

test.describe("Assets Page Tests", () => {
  let assetsPage: AssetsPage;

  test.beforeEach(async ({ page }) => {
    assetsPage = new AssetsPage(page);
    await assetsPage.navigate();
  });

  test.describe("List Functionality", () => {
    test("Displays the asset list on the first visit", async ({ page }) => {
      // Verify the asset list is visible
      const assetList = await assetsPage.getAssetList();
      await expect(assetList).toBeVisible();

      // Verify there is at least one asset card
      const assetCards = await assetsPage.getAssetCards();
      const assets = await assetCards.allTextContents();
      expect(assets.length).toBeGreaterThan(1);
    });
  });

  test.describe("Create Functionality", () => {
    test("Creates a new asset and verifies its visibility in the list", async ({ page }) => {
      // Open the create asset modal
      await assetsPage.openCreateAssetModal();  

      // Fill in the asset details
      const randomNumber = `${Math.random()}`.replace("0.", "");
      const assetTitle = `Test Dataset ${randomNumber}`;
      await assetsPage.fillAssetTitle(assetTitle);
      const autoGeneratedId = page.getByRole('textbox', { name: 'Asset ID' }) ;
      await expect(autoGeneratedId).toHaveValue(`test-dataset-${randomNumber}`);

      const assetId = `dataset-id-${randomNumber}`;
      await assetsPage.fillAssetId(assetId);

      await assetsPage.openAdvancedSection();
      await assetsPage.fillRequiredAssetFields();

      await assetsPage.openDataSourceSection();
      await assetsPage.fillHttpURL();

      // Submit the form
      await assetsPage.submitCreateAssetForm();

      // Verify the success message is displayed
      const successMessage = await assetsPage.waitForToastMessage("success");
      await expect(successMessage).toBeVisible();

      await assetsPage.searchAssets(assetTitle);
      const searchResults = await assetsPage.getSearchResults();

      await searchResults.nth(0).click() ;

      const organizationName = page.getByTestId("organizationName");
      await expect(organizationName).toHaveText(participantConfig.EDC_CURATOR_ORGANIZATION);
    });

    test.describe("Asset Data Sources", () => {
      test("Creates a new asset with GET HTTP and verifies its visibility in the list", async ({ page }) => {
        await assetsPage.openCreateAssetModal();

        const randomNumber = `${Math.random()}`.replace("0.", "");
        const assetTitle = `Test GET HTTP Dataset ${randomNumber}`;
        await assetsPage.fillAssetTitle(assetTitle);

        await assetsPage.openAdvancedSection();
        await assetsPage.fillRequiredAssetFields();

        await assetsPage.openDataSourceSection();
        await assetsPage.selectHttpType();
        await assetsPage.selectHttpMethod("GET");
        await assetsPage.fillHttpURL();

        await assetsPage.fillHttpPath() ;
        await assetsPage.addQueryParams();
        await assetsPage.addAuthHeaders();
        await assetsPage.addAdditionalHeaders();

        await assetsPage.submitCreateAssetForm();

        const successMessage = await assetsPage.waitForToastMessage("success");
        await expect(successMessage).toBeVisible();
      });

      test("Creates a new asset with POST HTTP and verifies its visibility in the list", async ({ page }) => {
        await assetsPage.openCreateAssetModal();

        const randomNumber = `${Math.random()}`.replace("0.", "");
        const assetTitle = `Test POST HTTP Dataset ${randomNumber}`;
        await assetsPage.fillAssetTitle(assetTitle);

        await assetsPage.openAdvancedSection();
        await assetsPage.fillRequiredAssetFields();

        await assetsPage.openDataSourceSection();
        await assetsPage.selectHttpType();
        await assetsPage.selectHttpMethod("POST");
        await assetsPage.fillHttpURL();

        await assetsPage.enableProxyQueryParams();
        await assetsPage.enableProxyPath();
        await assetsPage.enableProxyBody() ;
        
        await assetsPage.submitCreateAssetForm();

        const successMessage = await assetsPage.waitForToastMessage("success");
        await expect(successMessage).toBeVisible();
      });

      test("Creates a new S3 asset for a single object and verifies its visibility in the list", async ({ page }) => {
        await assetsPage.openCreateAssetModal();

        const randomNumber = `${Math.random()}`.replace("0.", "");
        const assetTitle = `Test S3 Single Object Dataset ${randomNumber}`;
        await assetsPage.fillAssetTitle(assetTitle);

        await assetsPage.openAdvancedSection();
        await assetsPage.fillRequiredAssetFields();

        await assetsPage.openDataSourceSection();
        await assetsPage.selectS3Type();
        await assetsPage.fillRequiredS3Datasource("single");

        await assetsPage.submitCreateAssetForm();

        const successMessage = await assetsPage.waitForToastMessage("success");
        await expect(successMessage).toBeVisible();
      });

      test("Creates a new S3 asset for multiple objects and verifies its visibility in the list", async ({ page }) => {
        await assetsPage.openCreateAssetModal();

        const randomNumber = `${Math.random()}`.replace("0.", "");
        const assetTitle = `Test S3 Multiple Objects Dataset ${randomNumber}`;
        await assetsPage.fillAssetTitle(assetTitle);

        await assetsPage.openAdvancedSection();
        await assetsPage.fillRequiredAssetFields();

        await assetsPage.openDataSourceSection();
        await assetsPage.selectS3Type();
        await assetsPage.fillRequiredS3Datasource("multiple");

        await assetsPage.submitCreateAssetForm();

        const successMessage = await assetsPage.waitForToastMessage("success");
        await expect(successMessage).toBeVisible();
      });

      test("Creates a new Azure asset for a single blob and verifies its visibility in the list", async ({ page }) => {
        await assetsPage.openCreateAssetModal();

        const randomNumber = `${Math.random()}`.replace("0.", "");
        const assetTitle = `Test Azure Single Blob Dataset ${randomNumber}`;
        await assetsPage.fillAssetTitle(assetTitle);

        await assetsPage.openAdvancedSection();
        await assetsPage.fillRequiredAssetFields();

        await assetsPage.openDataSourceSection();
        await assetsPage.selectAzureType();
        await assetsPage.fillRequiredAzureDatasource("single");

        await assetsPage.submitCreateAssetForm();

        const successMessage = await assetsPage.waitForToastMessage("success");
        await expect(successMessage).toBeVisible();
      });

      test("Creates a new Azure asset for multiple blobs and verifies its visibility in the list", async ({ page }) => {
        await assetsPage.openCreateAssetModal();

        const randomNumber = `${Math.random()}`.replace("0.", "");
        const assetTitle = `Test Azure Multiple Blobs Dataset ${randomNumber}`;
        await assetsPage.fillAssetTitle(assetTitle);

        await assetsPage.openAdvancedSection();
        await assetsPage.fillRequiredAssetFields();

        await assetsPage.openDataSourceSection();
        await assetsPage.selectAzureType();
        await assetsPage.fillRequiredAzureDatasource("multiple");

        await assetsPage.submitCreateAssetForm();

        const successMessage = await assetsPage.waitForToastMessage("success");
        await expect(successMessage).toBeVisible();
      });

      test("Creates a new asset with a Custom JSON block and verifies its visibility in the list", async ({ page }) => {
        await assetsPage.openCreateAssetModal();

        const randomNumber = `${Math.random()}`.replace("0.", "");
        const assetTitle = `Test Custom JSON Dataset ${randomNumber}`;
        await assetsPage.fillAssetTitle(assetTitle);

        await assetsPage.openAdvancedSection();
        await assetsPage.fillRequiredAssetFields();

        await assetsPage.openDataSourceSection();

        await assetsPage.selectCustomJsonType();
        await assetsPage.fillCustomJsonDatasource();

        await assetsPage.submitCreateAssetForm();

        const successMessage = await assetsPage.waitForToastMessage("success");
        await expect(successMessage).toBeVisible();
      });

      test("Creates a new asset with an On Request type and verifies its visibility in the list", async ({ page }) => {
        await assetsPage.openCreateAssetModal();

        const randomNumber = `${Math.random()}`.replace("0.", "");
        const assetTitle = `Test On Request Dataset ${randomNumber}`;
        await assetsPage.fillAssetTitle(assetTitle);

        await assetsPage.openAdvancedSection();
        await assetsPage.fillRequiredAssetFields();
        await assetsPage.openDataSourceSection();

        await assetsPage.selectOnRequestType();
        await assetsPage.fillOnRequestDatasource();

        await assetsPage.submitCreateAssetForm();

        const successMessage = await assetsPage.waitForToastMessage("success");
        await expect(successMessage).toBeVisible();
      });
    })
  });

  test.describe("Delete Functionality", () => {
    test("Deletes an asset and verifies it is removed from the list", async ({ page }) => {
      // Select an asset to delete
      const assetCards = await assetsPage.getAssetCards();
      const assetCard = assetCards.first();
      const assetName = (await assetCard.textContent()) || "";
      await assetCard.click();
      await assetsPage.submitDeleteAsset();

      // Confirm deletion
      await assetsPage.confirmDeleteAsset();

      // Verify the success message is displayed
      const successMessage = await assetsPage.waitForToastMessage("success");
      await expect(successMessage).toBeVisible();

      // Verify the asset is removed
      await expect(page.locator(assetsPage.assetListLocator).locator(assetsPage.assetCardLocator).filter({ hasText: assetName })).toHaveCount(0);
    });
  });

  test.describe("Edit Functionality", () => {
    test("Updates an asset and verifies the changes", async ({ page }) => {
      // Select an asset to view details
      const assetCards = await assetsPage.getAssetCards();
      const assetCard = assetCards.first();
      const originalTitle = await assetCard.locator('[data-testid="asset-title"]').textContent();
      const updatedTitle = `${originalTitle} - Updated`;
      const updatedDescription = "This is an updated description.";

      await assetCard.click();

      // Verify the "Edit" button is present in the asset details modal
      const editButton = await assetsPage.getEditButton();
      await expect(editButton).toBeVisible();
      await editButton.click() ;

      await page.waitForURL("assets/**/edit") ;
      await page.waitForResponse((response) => response.url().includes('/connector/management/v3/assets'))

      // Wait for form hydration — title field should be populated with existing asset title
      const titleInput = page.getByRole('textbox', { name: 'Title' });
      await expect(titleInput).not.toHaveValue('', { timeout: 30000 });

      await assetsPage.fillEditAssetForm(updatedTitle, updatedDescription);

      // Set up response listener BEFORE clicking submit to avoid race condition
      const updateResponsePromise = page.waitForResponse(
        (response) => response.url().includes('/connector/management/v3/assets') &&
                      !response.url().includes('/connector/management/v3/assets/') &&
                      response.request().method() === 'PUT'
      );
      await assetsPage.submitEditAssetForm();
      await updateResponsePromise;

      // Verify the success message is displayed
      const successMessage = await assetsPage.waitForToastMessage("success");
      await expect(successMessage).toBeVisible();
    });
  });

  test.describe("View Functionality", () => {
    test("Displays asset details correctly", async ({ page }) => {
      // Select an asset
      const assetCards = await assetsPage.getAssetCards();
      const assetCard = assetCards.first();
      await assetCard.click();

      // Verify details are displayed
      const assetDetails = page.locator(assetsPage.assetDialogLocator);
      await expect(assetDetails).toBeVisible();
      await expect(assetDetails.locator('text=Asset ID')).toBeVisible();
      await expect(assetDetails.locator('text=Participant ID')).toBeVisible();
    });
  });

  test.describe("Search Functionality", () => {
    test("should display search input and trigger button", async ({ page }) => {
      const searchInput = await assetsPage.getSearchInput();
      const searchTrigger = await assetsPage.getSearchTrigger();

      await expect(searchInput).toBeVisible();
      await expect(searchTrigger).toBeVisible();
    });

    test("should search for assets by title", async ({ page }) => {
      const initialAssets = await assetsPage.getAssetCards();
      const initialCount = await initialAssets.count();

      if (initialCount > 0) {
        const firstAsset = initialAssets.first();
        const firstAssetTitle = await firstAsset.locator('[data-testid="asset-title"]').textContent();
        const searchTerm = firstAssetTitle || 'test';

        await assetsPage.searchAssets(searchTerm);

        const searchResults = await assetsPage.getSearchResults();
        await expect(searchResults).toBeVisible();

        const results = await searchResults.allTextContents();
        const hasMatchingResult = results.some(result =>
          result.toLowerCase().includes(searchTerm.toLowerCase())
        );
        expect(hasMatchingResult).toBeTruthy();
      }
    });

    test("should clear search and show all assets", async ({ page }) => {
      await assetsPage.searchAssets('test');

      await assetsPage.clearSearch();

      const allAssets = await assetsPage.getAssetCards();
      await expect(allAssets.first()).toBeVisible();
    });

    test("should handle empty search results", async ({ page }) => {
      await assetsPage.searchAssets('nonexistentasset12345');

      const searchResults = await assetsPage.getSearchResults();
      const resultCount = await searchResults.count();
      expect(resultCount).toBeGreaterThanOrEqual(0);
    });
  });

  test.describe("Pagination Functionality", () => {
    test("should display pagination controls", async ({ page }) => {
      const paginationInfo = await assetsPage.getPaginationInfo();
      await expect(paginationInfo).toBeVisible();
    });

    test("should navigate to next page when available", async ({ page }) => {
      const initialLastIndex = await assetsPage.getLastElementIndex();
      const isNextEnabled = await assetsPage.isNextPageEnabled();

      if (isNextEnabled) {
        await assetsPage.goToNextPage();

        const newFirstIndex = await assetsPage.getFirstElementIndex();
        expect(newFirstIndex).toBe(initialLastIndex + 1);
      } else {
        const totalLastIndex = await assetsPage.getLastElementIndex();
        expect(initialLastIndex).toBe(totalLastIndex);
      }
    });

    test("should navigate to previous page when available", async ({ page }) => {
      const isNextEnabled = await assetsPage.isNextPageEnabled();
      if (isNextEnabled) {
        await assetsPage.goToNextPage();
        const firstItemInNextPage = await assetsPage.getFirstElementIndex();

        await assetsPage.goToPreviousPage();
        const firstItemInPreviousPage = await assetsPage.getFirstElementIndex();

        expect(firstItemInPreviousPage).toBe(firstItemInNextPage - MAX_ITEMS);
      } else {
        const isPrevEnabled = await assetsPage.isPreviousPageEnabled();
        const currentFirstIndex = await assetsPage.getFirstElementIndex();

        if (currentFirstIndex === 1) {
          expect(isPrevEnabled).toBeFalsy();
        }
      }
    });

    test("should disable previous button on first page", async ({ page }) => {
      const currentFirstIndex = await assetsPage.getFirstElementIndex();

      if (currentFirstIndex === 1) {
        const isPrevEnabled = await assetsPage.isPreviousPageEnabled();
        expect(isPrevEnabled).toBeFalsy();
      }
    });

    test("should disable next button on last page", async ({ page }) => {
      let pages = 0;
      while (await assetsPage.isNextPageEnabled() && pages < 50) {
        await assetsPage.goToNextPage();
        pages++;
      }

      const isNextEnabled = await assetsPage.isNextPageEnabled();
      expect(isNextEnabled).toBeFalsy();
    });

    test("should maintain search results across pagination", async ({ page }) => {
      const searchTerm = "test asset" ;
      await assetsPage.searchAssets(searchTerm);

      const isNextEnabled = await assetsPage.isNextPageEnabled();
      if (isNextEnabled) {
        await assetsPage.goToNextPage();

        const searchInput = await assetsPage.getSearchInput();
        const searchValue = searchInput;
        await expect(searchValue).toHaveValue(searchTerm);
      }
    });
  });
});
