name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create .npmrc
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
        echo "@think-it:registry=https://npm.pkg.github.com" >> .npmrc

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build
