name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: echo -e "@think-it-labs:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${{ secrets.THINKIT_TOKEN }}" >> ./.npmrc

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build
